routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
*/

if (version_compare(PHP_VERSION, '7.2.0', '>=')) {
    // Ignores notices and reports all other kinds... and warnings
    error_reporting(E_ALL ^ E_NOTICE ^ E_WARNING);
    // error_reporting(E_ALL ^ E_WARNING); // Maybe this is enough
 }
Route::get('/', 'AdminController@dashboard')->name('index');
Route::get('/dashboard', 'AdminController@dashboard')->name('dashboard');
Route::get('/heatmap', 'AdminController@heatmap')->name('heatmap');
Route::get('/translation',  'AdminController@translation')->name('translation');

Route::group(['as' => 'dispatcher.', 'prefix' => 'dispatcher'], function () {
	Route::get('/', 'DispatcherController@index')->name('index');
	Route::post('/', 'DispatcherController@store')->name('store');
    Route::get('/trips', 'DispatcherController@trips')->name('trips');
    Route::get('/cancelled', 'DispatcherController@cancelled')->name('cancelled');
	Route::get('/cancel', 'DispatcherController@cancel')->name('cancel');
	Route::get('/trips/{trip}/{provider}', 'DispatcherController@assign')->name('assign');
	Route::get('/users', 'DispatcherController@users')->name('users');
	Route::get('/providers', 'DispatcherController@providers')->name('providers');
});

Route::resource('user', 'Resource\UserResource');
Route::resource('dispatch-manager', 'Resource\DispatcherResource');
Route::resource('account-manager', 'Resource\AccountResource');
Route::resource('fleet', 'Resource\FleetResource');
Route::resource('provider', 'Resource\ProviderResource');
Route::resource('document', 'Resource\DocumentResource');
Route::resource('service', 'Resource\ServiceResource');
Route::resource('promocode', 'Resource\PromocodeResource');
Route::resource('time', 'Resource\TimeResource');
Route::resource('packagetype', 'Resource\PackageTypeResource');
Route::resource('servicerentalhourpackage', 'Resource\ServiceRentalHourPackageController');

//// user seleted delete
Route::post('user/seleted_delete', 'Resource\UserResource@user_seleted_delete');

//// All User Export Excel
Route::get('user/export/excel', 'Resource\UserResource@user_export_excel');

//// Provider seleted delete
Route::post('provider/seleted_delete', 'Resource\ProviderResource@provider_seleted_delete');



// geo fencing set city base drag location
Route::resource('geo-fencing', 'Resource\GeoFencingResource');

Route::get('/timelist', 'AdminController@time_list');

//subadmin
Route::resource('roles', 'Resource\RolesResource');
Route::resource('subadmin', 'SubAdminController');
Route::get('roles/permission/{id}', 'Resource\RolesResource@permission');
Route::post('roles/permission/store/{id}', 'Resource\RolesResource@store_permission')->name('permission.store');

Route::group(['as' => 'provider.'], function () {
    Route::get('review/provider', 'AdminController@provider_review')->name('review');
    Route::get('provider/{id}/approve', 'Resource\ProviderResource@approve')->name('approve');
    Route::get('provider/{id}/disapprove', 'Resource\ProviderResource@disapprove')->name('disapprove');
    Route::get('provider/{id}/request', 'Resource\ProviderResource@request')->name('request');
    Route::get('provider/{id}/statement', 'Resource\ProviderResource@statement')->name('statement');
    Route::resource('provider/{provider}/document', 'Resource\ProviderDocumentResource');
    Route::delete('provider/{provider}/service/{document}', 'Resource\ProviderDocumentResource@service_destroy')->name('document.service');
    Route::post('provider/document/upload/{provider}', 'Resource\ProviderDocumentResource@provider_document_upload')->name('document.upload');
    Route::get('provider/make/online', 'Resource\ProviderResource@make_online_provider')->name('online');
});

Route::get('review/user', 'AdminController@user_review')->name('user.review');
Route::get('user/{id}/request', 'Resource\UserResource@request')->name('user.request');

Route::get('map', 'AdminController@map_index')->name('map.index');
Route::get('map/ajax', 'AdminController@map_ajax')->name('map.ajax');
Route::post('map/search/name/ajax', 'AdminController@map_search_name_ajax')->name('map.search.ajax');

Route::get('settings', 'AdminController@settings')->name('settings');
Route::post('settings/store', 'AdminController@settings_store')->name('settings.store');
Route::get('settings/payment', 'AdminController@settings_payment')->name('settings.payment');
Route::post('settings/payment', 'AdminController@settings_payment_store')->name('settings.payment.store');

Route::get('profile', 'AdminController@profile')->name('profile');
Route::post('profile', 'AdminController@profile_update')->name('profile.update');

Route::get('password', 'AdminController@password')->name('password');
Route::post('password', 'AdminController@password_update')->name('password.update');

Route::get('payment', 'AdminController@payment')->name('payment');

// statements

Route::get('/statement', 'AdminController@statement')->name('ride.statement');
Route::get('/statement/provider', 'AdminController@statement_provider')->name('ride.statement.provider');
Route::get('/statement/today', 'AdminController@statement_today')->name('ride.statement.today');
Route::get('/statement/monthly', 'AdminController@statement_monthly')->name('ride.statement.monthly');
Route::get('/statement/yearly', 'AdminController@statement_yearly')->name('ride.statement.yearly');


// Static Pages - Post updates to pages.update when adding new static pages.

Route::get('/help', 'AdminController@help')->name('help');
Route::get('/faq', 'AdminController@faq')->name('faq');
Route::get('/send/push', 'AdminController@push')->name('push');
Route::post('/send/push', 'AdminController@send_push')->name('send.push');
Route::get('/privacy', 'AdminController@privacy')->name('privacy');
Route::get('/terms', 'AdminController@terms')->name('terms');
Route::get('/help', 'AdminController@help')->name('help');
Route::get('/offers', 'AdminController@offers')->name('offers');
Route::get('/about_us', 'AdminController@about_us')->name('about_us');
Route::post('/pages', 'AdminController@pages')->name('pages.update');
Route::resource('requests', 'Resource\TripResource');
Route::post('requests/seleted_cancelled_delete', 'Resource\TripResource@request_seleted_cancelled_delete'); 
Route::get('scheduled', 'Resource\TripResource@scheduled')->name('requests.scheduled');

Route::get('push', 'AdminController@push_index')->name('push.index');
Route::post('push', 'AdminController@push_store')->name('push.store');



Route::get('/dispatch', function () {
    return view('admin.dispatch.index');
});

Route::get('/cancelled', function () {
    return view('admin.dispatch.cancelled');
});

Route::get('/ongoing', function () {
    return view('admin.dispatch.ongoing');
});

Route::get('/schedule', function () {
    return view('admin.dispatch.schedule');
});

Route::get('/add', function () {
    return view('admin.dispatch.add');
});

Route::get('/assign-provider', function () {
    return view('admin.dispatch.assign-provider');
});

Route::get('/dispute', function () {
    return view('admin.dispute.index');
});

Route::get('/dispute-create', function () {
    return view('admin.dispute.create');
});

Route::get('/dispute-edit', function () {
    return view('admin.dispute.edit');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| User Authentication Routes
|--------------------------------------------------------------------------
*/


Auth::routes();

Route::get('/versions' , 'UserApiController@versions');

Route::post('/login/otp' , 'UserApiController@login_otp');

Route::get('auth/facebook', 'Auth\SocialLoginController@redirectToFaceBook');
Route::get('auth/facebook/callback', 'Auth\SocialLoginController@handleFacebookCallback');
Route::get('auth/google', 'Auth\SocialLoginController@redirectToGoogle');
Route::get('auth/google/callback', 'Auth\SocialLoginController@handleGoogleCallback');
Route::post('account/kit', 'Auth\SocialLoginController@account_kit')->name('account.kit');

Route::post('user/check/mobile', 'UserApiController@user_check_mobile')->name('user.check.mobile');
Route::post('provider/check/mobile', 'ProviderAuth\TokenController@provider_check_mobile')->name('provider.check.mobile');

/*
|--------------------------------------------------------------------------
| Provider Authentication Routes
|--------------------------------------------------------------------------
*/

Route::group(['prefix' => 'provider'], function () {

    Route::get('auth/facebook', 'Auth\SocialLoginController@providerToFaceBook');
    Route::get('auth/google', 'Auth\SocialLoginController@providerToGoogle');

    Route::get('/login', 'ProviderAuth\LoginController@showLoginForm');
    Route::post('/login', 'ProviderAuth\LoginController@login');

    Route::post('/login/otp', 'ProviderAuth\LoginController@login_otp');

    Route::post('/logout', 'ProviderAuth\LoginController@logout');

    Route::get('/register', 'ProviderAuth\RegisterController@showRegistrationForm');
    Route::post('/register', 'ProviderAuth\RegisterController@register');

    Route::post('/password/email', 'ProviderAuth\ForgotPasswordController@sendResetLinkEmail');
    Route::post('/password/reset', 'ProviderAuth\ResetPasswordController@reset');
    Route::get('/password/reset', 'ProviderAuth\ForgotPasswordController@showLinkRequestForm');
    Route::get('/password/reset/{token}', 'ProviderAuth\ResetPasswordController@showResetForm');
});

/*
|--------------------------------------------------------------------------
| Admin Authentication Routes
|--------------------------------------------------------------------------
*/

Route::group(['prefix' => 'admin'], function () {
    Route::get('/login', 'AdminAuth\LoginController@showLoginForm');
    Route::post('/login', 'AdminAuth\LoginController@login');
    Route::post('/logout', 'AdminAuth\LoginController@logout');

    Route::post('/password/email', 'AdminAuth\ForgotPasswordController@sendResetLinkEmail');
    Route::post('/password/reset', 'AdminAuth\ResetPasswordController@reset');
    Route::get('/password/reset', 'AdminAuth\ForgotPasswordController@showLinkRequestForm');
    Route::get('/password/reset/{token}', 'AdminAuth\ResetPasswordController@showResetForm');
});

/*
|--------------------------------------------------------------------------
| Dispatcher Authentication Routes
|--------------------------------------------------------------------------
*/

Route::group(['prefix' => 'dispatcher'], function () {
    Route::get('/login', 'DispatcherAuth\LoginController@showLoginForm');
    Route::post('/login', 'DispatcherAuth\LoginController@login');
    Route::post('/logout', 'DispatcherAuth\LoginController@logout');

    Route::post('/password/email', 'DispatcherAuth\ForgotPasswordController@sendResetLinkEmail');
    Route::post('/password/reset', 'DispatcherAuth\ResetPasswordController@reset');
    Route::get('/password/reset', 'DispatcherAuth\ForgotPasswordController@showLinkRequestForm');
    Route::get('/password/reset/{token}', 'DispatcherAuth\ResetPasswordController@showResetForm');
});

/*
|--------------------------------------------------------------------------
| Fleet Authentication Routes
|--------------------------------------------------------------------------
*/


Route::group(['prefix' => 'fleet'], function () {
    Route::get('/login', 'FleetAuth\LoginController@showLoginForm');
    Route::post('/login', 'FleetAuth\LoginController@login');
    Route::post('/logout', 'FleetAuth\LoginController@logout');

    Route::post('/password/email', 'FleetAuth\ForgotPasswordController@sendResetLinkEmail');
    Route::post('/password/reset', 'FleetAuth\ResetPasswordController@reset');
    Route::get('/password/reset', 'FleetAuth\ForgotPasswordController@showLinkRequestForm');
    Route::get('/password/reset/{token}', 'FleetAuth\ResetPasswordController@showResetForm');
});

/*
|--------------------------------------------------------------------------
| Account Authentication Routes
|--------------------------------------------------------------------------
*/


Route::group(['prefix' => 'account'], function () {
    Route::get('/login', 'AccountAuth\LoginController@showLoginForm');
    Route::post('/login', 'AccountAuth\LoginController@login');
    Route::post('/logout', 'AccountAuth\LoginController@logout');

    Route::get('/register', 'AccountAuth\RegisterController@showRegistrationForm');
    Route::post('/register', 'AccountAuth\RegisterController@register');

    Route::post('/password/email', 'AccountAuth\ForgotPasswordController@sendResetLinkEmail');
    Route::post('/password/reset', 'AccountAuth\ResetPasswordController@reset');
    Route::get('/password/reset', 'AccountAuth\ForgotPasswordController@showLinkRequestForm');
    Route::get('/password/reset/{token}', 'AccountAuth\ResetPasswordController@showResetForm');
});

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/
Route::get('/invoice/{id}', 'ProviderResources\TripController@invoice');
Route::get('/', function () {
    return view('index');
});

Route::get('/initsetup', function () {
    return Setting::all();
});

Route::get('/ride', function () {
    $services = App\ServiceType::get();
    return view('ride',compact('services'));
});

// Route::get('/ride', 'Auth\RegisterController@ride');

Route::get('/drive', function () {
    return view('drive');
});

Route::get('privacy', function () {
    $page = 'page_privacy';
    $title = 'Privacy Policy';
    return view('static', compact('page', 'title'));
});
Route::get('help', function () {
    $page = 'page_Help';
    $title = 'Help';
    return view('static', compact('page', 'title'));
});
Route::get('terms', function () {
    $page = 'terms';
    $title = 'Terms & Condition';
    return view('static', compact('page', 'title'));
});

Route::get('offers', function () {
    $page = 'offers';
    $title = 'Offers in Nagpur';
    return view('static', compact('page', 'title'));
});

Route::get('about_us', function () {
    $page = 'about_us';
    $title = 'About Us';
    return view('static', compact('page', 'title'));
});
Route::get('faq', function () {
    $page = 'faq';
    $title = 'FAQ';
    return view('static', compact('page', 'title'));
});


Route::get('/estimated/fare', 'AdminController@estimated_fare')->name('estimated.fare');


/*
|--------------------------------------------------------------------------
| User Routes
|--------------------------------------------------------------------------
*/

Route::get('/dashboard', 'HomeController@index');
Route::get('/rental_package', 'HomeController@rental_package');
Route::get('/hour/{id}', 'UserApiController@pricing_logic');

// user profiles
Route::get('/profile', 'HomeController@profile');
Route::get('/edit/profile', 'HomeController@edit_profile');
Route::post('/profile', 'HomeController@update_profile');

// update password
Route::get('/change/password', 'HomeController@change_password');
Route::post('/change/password', 'HomeController@update_password');

// ride
Route::get('/confirm/ride', 'RideController@confirm_ride');
Route::post('/create/ride', 'RideController@create_ride');
Route::post('/cancel/ride', 'RideController@cancel_ride');
Route::get('/onride', 'RideController@onride');
Route::post('/payment', 'PaymentController@payment');
Route::post('/rate', 'RideController@rate');

// status check
Route::get('/status', 'RideController@status');

// trips
Route::get('/trips', 'HomeController@trips');
Route::get('/upcoming/trips', 'HomeController@upcoming_trips');

// wallet
Route::get('/wallet', 'HomeController@wallet');
Route::post('/add/money', 'PaymentController@add_money');

// payment
Route::get('/payment', 'HomeController@payment');

// card
Route::resource('card', 'Resource\CardResource');

// promotions
Route::get('/promotions', 'HomeController@promotions_index')->name('promocodes.index');
Route::post('/promotions', 'HomeController@promotions_store')->name('promocodes.store');

Route::post('/fare' , 'UserApiController@fare');

//CC Avanue
Route::get('/ccavanue' , 'UserApiController@ccavanue_trip');
Route::post('/indipay/ccavanue/web/response' , 'PaymentController@ccavanue_web_response');
Route::post('/indipay/ccavanue/web/cancel/response' , 'PaymentController@ccavanue_web_cancel_response');

// Mobile API

// RSA key generate
Route::post('/rsa/key' , 'PaymentController@rsa_key_generate');

Route::post('/indipay/ccavanue/response' , 'PaymentController@ccavanue_response');
Route::post('/indipay/ccavanue/cancel/response' , 'PaymentController@ccavanue_cancel_response');

app/ServiceRentalHourPackage.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ServiceRentalHourPackage extends Model
{
     protected $table = 'service_rental_hour_packages';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'service_type_id','hour','km','price'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        	'created_at','updated_at'
    ];
}

resources/views/admin/servicerentalhourpackage/create.blade.php
@extends('admin.layout.base')

@section('title', 'Add Rental Hour Package ')

@section('content')

<div class="content-area py-1">
    <div class="container-fluid">
        <div class="box box-block bg-white">
            <a href="{{ route('admin.servicerentalhourpackage.index') }}?service_type_id={{Request::get('service_type_id')}}" class="btn btn-default pull-right"><i class="fa fa-angle-left"></i> @lang('admin.back')</a>

            <h5 style="margin-bottom: 2em;">Add Rental Hour Package</h5>

            <form class="form-horizontal" action="{{route('admin.servicerentalhourpackage.store')}}" method="POST" enctype="multipart/form-data" role="form">
                {{csrf_field()}}
                <div class="form-group row">
                    <label for="hour" class="col-xs-12 col-form-label">Hour</label>
                    <div class="col-xs-10">
                        <input class="form-control" type="text" value="{{ old('hour') }}" name="hour" required id="hour" placeholder="Hour">
                    </div>
                </div>

                <div class="form-group row">
                    <label for="km" class="col-xs-12 col-form-label">KM</label>
                    <div class="col-xs-10">
                        <input class="form-control" type="text" value="{{ old('km') }}" name="km" required id="km" placeholder="KM">
                    </div>
                </div>  
                <div class="form-group row">
                    <label for="price" class="col-xs-12 col-form-label">Price</label>
                    <div class="col-xs-10">
                        <input class="form-control" type="number" value="{{ old('price') }}" name="price" required id="price" placeholder="Price"> 
                        <input class="form-control" type="hidden" value="{{ Request::get('service_type_id') }}" name="service_type_id">
                    </div>
                </div>               
                
                <div class="form-group row">
                    <label for="zipcode" class="col-xs-12 col-form-label"></label>
                    <div class="col-xs-10">
                        <button type="submit" class="btn btn-primary">Add Rental Hour Package</button>
                        <a href="{{route('admin.servicerentalhourpackage.index')}}" class="btn btn-default">@lang('admin.cancel')</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@endsection

resources/views/admin/servicerentalhourpackage/edit.blade.php
@extends('admin.layout.base')

@section('title', 'Update Rental Hour Package ')

@section('content')

<div class="content-area py-1">
    <div class="container-fluid">
    	<div class="box box-block bg-white">
    	    <a href="{{ route('admin.servicerentalhourpackage.index') }}?service_type_id={{$package->service_type_id}}" class="btn btn-default pull-right"><i class="fa fa-angle-left"></i> @lang('admin.back')</a>

			<h5 style="margin-bottom: 2em;">Rental Hour Package</h5>

            <form class="form-horizontal" action="{{route('admin.servicerentalhourpackage.update', $package->id )}}" method="POST" enctype="multipart/form-data" role="form">
            	{{csrf_field()}}
            	<input type="hidden" name="_method" value="PATCH">
				<div class="form-group row">
					<label for="hour" class="col-xs-2 col-form-label">Hour</label>
					<div class="col-xs-10">
						<input class="form-control" type="text" value="{{ $package->hour }}" name="hour" required id="hour" placeholder="Enter Hour">
					</div>
				</div>
				<div class="form-group row">
					<label for="km" class="col-xs-2 col-form-label">KM</label>
					<div class="col-xs-10">
						<input class="form-control" type="text" value="{{ $package->km }}" name="km" required id="km" placeholder="Enter KM">
					</div>
				</div> 
				<div class="form-group row">
					<label for="price" class="col-xs-2 col-form-label">Price</label>
					<div class="col-xs-10">
						<input class="form-control" type="number" value="{{ $package->price }}" name="price" required id="price" placeholder="Enter Price">
					</div>
				</div>
				

				<div class="form-group row">
					<label for="feedback" class="col-xs-2 col-form-label"></label>
					<div class="col-xs-10">
						<button type="submit" class="btn btn-primary">Update Rental Hour Package</button>
						<a href="{{route('admin.servicerentalhourpackage.index')}}" class="btn btn-default">@lang('admin.cancel')</a>
					</div>
				</div>
			</form>
		</div>
    </div>
</div>

@endsection

resources/views/admin/servicerentalhourpackage/index.blade.php
@extends('admin.layout.base')

@section('title', 'Service Rental Hour Package ')

@section('content')

    <div class="content-area py-1">
        <div class="container-fluid">
            
            <div class="box box-block bg-white">
                <h5 class="mb-1">Rental Hour Package</h5>
                <a href="{{ route('admin.servicerentalhourpackage.create') }}?service_type_id={{Request::get('service_type_id')}}" style="margin-left: 1em;" class="btn btn-primary pull-right"><i class="fa fa-plus"></i>Add Rental Hour Package</a>
                <table class="table table-striped table-bordered dataTable" id="table-2">
                    <thead>
                        <tr>
                            <th>@lang('admin.id')</th>
                            <th>Hour</th>
                            <th>KM</th>
                            <th>Price</th>
                            <th>Action</th>
                            
                        </tr>
                    </thead>
                    <tbody>
                    @foreach($package as $index => $packages)
                        <tr>
                            <td>{{$index + 1}}</td>
                            <td>{{$packages->hour}}</td>
                            <td>{{$packages->km}}</td>
                            <td>{{$packages->price}}</td>
                            
                            
                            <td>
                                <form action="{{ route('admin.servicerentalhourpackage.destroy', $packages->id) }}" method="POST">
                                    {{ csrf_field() }}
                                    <input type="hidden" name="_method" value="DELETE">
                                    @if( Setting::get('demo_mode') == 0)
                                    <a href="{{ route('admin.servicerentalhourpackage.edit', $packages->id) }}" class="btn btn-info"><i class="fa fa-pencil"></i> @lang('admin.edit')</a>
                                    <button class="btn btn-danger" onclick="return confirm('Are you sure?')"><i class="fa fa-trash"></i> @lang('admin.delete')</button>
                                    @endif
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>@lang('admin.id')</th>
                            <th>Hour</th>
                            <th>KM</th>
                            <th>Price</th>
                            <th>Action</th> 
                            
                        </tr>
                    </tfoot>
                </table>
            </div>
            
        </div>
    </div>
@endsection